 import "../../globals.css";

// import "../globals.css"
export const metadata = {
  title: "Shop Admin",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
